### ISSUE TITLE
fsniff window sizing/pattern matching

### ISSUE THREAD

**Issue by nikitamog** [iogf/vy#28]
fsniff has difficulties recognizing directory names with periods "." in them when pattern matching.

When fsniff matches a long file path, it resizes the window width. This does not size back to the original width when out of focus.

**Comment by iogf** [comment]
well, about the '.' periods, i have tested it here and it seems to be working correctly as expected. it escapes '.' when it sends the pattern to the underlying locate program. 

Regarding the window resizing i dont fully understand what you meant.
