### ISSUE TITLE
Mac OS X support: Replacing the apostrophe bind with something else

### ISSUE THREAD

**Issue by blha303** [iogf/vy#3]
I encountered this error when trying to run vy for the first time (after fixing idiotic dependency errors):

```
_tkinter.TclError: bad event type or keysym "apostrophe"
```

The root of the problem (as stated in [this Hacker News](https://news.ycombinator.com/item?id=10157832) post's top comment, the first result in a google search) is that apparently OSX's Tkinter doesn't have a key bind for apostrophe. Replacing it with something unused like plus as in [this commit](https://github.com/blha303/vy/commit/be7d6f33b057d983369460c98088a92f3c7a85cd) fixes that issue. Worthwhile looking into or finding a cross-platform solution?

**Comment by iogf** [comment]
Hi.  Thank you.  I will pick up a better key.  I will do it tomorrow i had some problems.  I will be back tomorrow.  Which key would you suggest? 

Sent from my Samsung Galaxy smartphone.

I encountered this error when trying to run vy for the first time (after fixing idiotic dependency errors): _tkinter.TclError: bad event type or keysym "apostrophe" The root of the problem (as stated in this Hacker News post's top comment, the first result in a google search) is that apparently OSX's Tkinter doesn't have a key bind for apostrophe. Replacing it with something unused like plus as in this commit fixes that issue. Worthwhile looking into or finding a cross-platform solution? —Reply to this email directly or view it on GitHub.

**Comment by blha303** [comment]
I suggested plus because it was unbound, but it may not be convenient enough. I'll leave it to you to decide.

**Comment by iogf** [comment]
i replaced for KeyPress-space
